use strict;
use warnings;
package RT::Extension::ListAllEmailRecipients;

our $VERSION = '0.03';

=head1 NAME

RT-Extension-ListAllEmailRecipients - List email recipients in the
body of RT email

=head1 DESCRIPTION

ListAllEmailRecipients searches for recipients in the headers on email
messages generated by RT and replaces a template placeholder with
the comma-delimited list of email recipients in the email message
body.

=head1 RT VERSION

Works with RT 4.2

=head1 INSTALLATION

=over

=item C<perl Makefile.PL>

=item C<make>

=item C<make install>

May need root permissions

=item Edit your F</opt/rt4/etc/RT_SiteConfig.pm>

If you are using RT 4.2 or greater, add this line:

    Plugin('RT::Extension::ListAllEmailRecipients');

=item Clear your mason cache

    rm -rf /opt/rt4/var/mason_data/obj

=item Restart your webserver

=item Modify your templates as described below.

=back

=head1 USAGE

ListEmailReceipients adds functionality to any RT scrip that uses
the default 'Notify' action. For these notification scrips, you
can add the placeholder C<RT-INSERT-RECIPIENTS> to your existing
notification template and it will be replace with a list of all
recipients on that email when RT sends out the notification.

For example, you could add this to your C<Correspondence> template:

    The following people received this email:
    RT-INSERT-RECIPIENTS

and the resulting email will look like:

    The following people received this email:
    user1@example.com, user2@example.com

=head1 AUTHOR

Best Practical Solutions, LLC E<lt>modules@bestpractical.comE<gt>

=head1 BUGS

Contact Best Practical Solutions at contact@bestpractical.com with
questions about this extension.

=head1 LICENSE AND COPYRIGHT

This software is Copyright (c) 2016 by Best Practical Solutions, LLC

This is free software, licensed under:

  The GNU General Public License, Version 2, June 1991

=cut

1;
